---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgAy343Ubt3OjL851W9f5Qb9oFeiSTtmtHthUxwKzEsrRbhAMJO6HXgKKldMGyTr0Jf3xvwiyjnwakKhqbUtEk3pURy7iVkaZ+sdsPpGysToxHxj+lotf4GWac0KDF3YZzgL9uWriL4o5+yxI2+Dy+z02RaIB7R35qADF8C9TGBJzxw0h8sJkvfOn74xfKhWtsNU9Ne6B2Qql4GyJ5fTxx9rmNjvz2aBkq1TrRaFon/8oR+LlGGf011SRPMT/Zgz4403Ki/FWBo2z0JyeZBpbEl5n5Kbsm2FFrDYT07378/DAaxOmr271OCZFuzruMk+JHmdO4Hqzs2rbayW65DC0xb31jY9yH0upIx+kKRKM3EIdFo+mxRf/gHCXDy8+tNsrgLcOzzFL1pAFJOuZYTXNdKNn65InwtUac+hKzAxcS8ANV6ingFVDqOBagyoNwpWeQaCwMk/+nIJ0PqGKtLLv6S5nI4MyPayd+iwPitkXDnVkvS3Oh3VqhN2tXZtCpeF0iw+FhULM4BmQGw/VLDV/ZhL/2tzQZWbyl/k8zhO1isTmYGFSDMo+w68r0UTpSQ1pAMlFfdBiMz9PlH7YGPLOrL9VHN+I122jSwjer6osraprSQ52OtAXM6rG0weHNtJu+YF4NSzv6bS5qPOYjQAqu+R4vIaed1Yro98+V4uj4IU9Guvkk+trzk6MRpCA8cCBodfj20Vb7vmPwAqlFYRADjZIMBmZKzkcm/f
  template:
    metadata:
      name: db-credentials
      namespace: dev
    type: Opaque
