apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV_NAME
              value: "{{ .Values.envName }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: db-password
