apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # Helm will automatically encrypt the password into base64 for Kubernetes
  db-password: {{ .Values.dbPassword | b64enc | quote }}
